version: '3.8'

services:
  gateway:
    build:
      context: ./AlbinMicroService.Gateway # Path to your API Gateway project
      dockerfile: Dockerfile
    ports:
      - "9001:9001" # HTTP
      - "9002:9002" # HTTPS
    depends_on:
      - users
      - master
      - admin
    networks:
      - microservices-network

  users:
    build:
      context: ./AlbinMicroService.Users
      dockerfile: Dockerfile
    ports:
      - "8001:8001" # HTTP (Replace with the actual HTTP port from Program.cs)
      - "8002:8002" # HTTPS (Replace with the actual HTTPS port from Program.cs)
    networks:
      - microservices-network

  master:
    build:
      context: ./AlbinMicroService.MasterData
      dockerfile: Dockerfile
    ports:
      - "8003:8003" # HTTP
      - "8004:8004" # HTTPS
    networks:
      - microservices-network
      
  admin:
    build:
      context: ./AlbinMicroService.Administration
      dockerfile: Dockerfile
    ports:
      - "8005:8005" # HTTP
      - "8006:8006" # HTTPS
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge