services:
  gateway:
    container_name: gateway-container
    build:
      context: .
      dockerfile: AlbinMicroService.Gateway/Dockerfile
    image: gateway-image
    ports:
      - "9001:9001"
    depends_on:
      - user-service
      - master-service
      - admin-service
    networks:
      - backend

  user-service:
    container_name: user-container
    build:
      context: .
      dockerfile: AlbinMicroService.Users/Dockerfile
    image: user-image
    ports:
      - "8001:8001"
    networks:
      - backend

  master-service:
    container_name: master-container
    build:
      context: .
      dockerfile: AlbinMicroService.MasterData/Dockerfile
    image: master-image
    ports:
      - "8003:8003"
    networks:
      - backend

  admin-service:
    container_name: admin-container
    build:
      context: .
      dockerfile: AlbinMicroService.Administration/Dockerfile
    image: admin-image
    ports:
      - "8005:8005"
    networks:
      - backend

networks:
  backend:
    driver: bridge
