CREATE TABLE users (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    IsVerified BOOLEAN NOT NULL DEFAULT FALSE,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DeletedAt DATETIME NULL
);
-----
CREATE TABLE user_profiles (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    UserId BIGINT NOT NULL,
    FirstName VARCHAR(255) NOT NULL DEFAULT '',
    LastName VARCHAR(255) NOT NULL DEFAULT '',
    PhoneNumber VARCHAR(20) NULL,
    ProfilePicture TEXT NULL,
    FOREIGN KEY (UserId) REFERENCES users(Id) ON DELETE CASCADE
);
------------
CREATE TABLE user_addresses (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    UserId BIGINT NOT NULL,
    AddressLine1 VARCHAR(255) NOT NULL DEFAULT '',
    AddressLine2 VARCHAR(255) NULL,
    City VARCHAR(100) NOT NULL DEFAULT '',
    State VARCHAR(100) NOT NULL DEFAULT '',
    ZipCode VARCHAR(20) NOT NULL DEFAULT '',
    Country VARCHAR(100) NOT NULL DEFAULT '',
    FOREIGN KEY (UserId) REFERENCES users(Id) ON DELETE CASCADE
);
----
CREATE TABLE user_activity_logs (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    UserId BIGINT NOT NULL,
    ActivityType VARCHAR(255) NOT NULL DEFAULT '',
    ActivityDescription TEXT NOT NULL,
    ActivityDate DATETIME NULL,
    FOREIGN KEY (UserId) REFERENCES users(Id) ON DELETE CASCADE
);
---
CREATE TABLE user_roles (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    UserId BIGINT NOT NULL,
    Role VARCHAR(100) NOT NULL DEFAULT '',
    Permissions TEXT NULL,
    FOREIGN KEY (UserId) REFERENCES users(Id) ON DELETE CASCADE
);
---------
CREATE TABLE user_security (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    UserId BIGINT NOT NULL,
    VerificationToken VARCHAR(255) NULL,
    PasswordResetToken VARCHAR(255) NULL,
    PasswordResetExpiresAt DATETIME NULL,
    FailedLoginAttempts INT NOT NULL DEFAULT 0,
    LastLoginAt DATETIME NULL,
    FOREIGN KEY (UserId) REFERENCES users(Id) ON DELETE CASCADE
);
---
CREATE TABLE user_social_auth (
    Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    UserId BIGINT NOT NULL,
    Provider VARCHAR(255) NOT NULL DEFAULT '',
    ProviderId VARCHAR(255) NOT NULL DEFAULT '',
    FOREIGN KEY (UserId) REFERENCES users(Id) ON DELETE CASCADE
);
