using MailKit.Net.Smtp;
using MimeKit;

namespace AlbinMicroService.Core.Utilities
{
    public static class StaticMeths
    {
        public static void SetGlobalWebAppMode(bool isDev, bool isStaging, bool isProduction)
        {
            StaticProps.GlobalWebAppRunningMode.IsDev = isDev;
            StaticProps.GlobalWebAppRunningMode.IsStaging = isStaging;
            StaticProps.GlobalWebAppRunningMode.IsProduction = isProduction;
        }

        public static T ConvertType<T>(object value)
        {
            return (T)Convert.ChangeType(value, typeof(T));
        }

        public static int GetPropertyCount(object obj)
        {
            if (obj == null)
            {
                return 0;
            }

            // Get the type of the object and count the properties
            return obj.GetType().GetProperties().Length;
        }

        public static string GetNullOrEmptyOrWhiteSpaceErrorText(string value = "")
        {
            return value + " cannot be null or empty or whitespace.";
        }
    }

    public interface IDynamicMeths
    {
        /// <summary>
        /// Hashes a string using Argon2.
        /// </summary>
        /// <param name="input"></param>
        /// <returns>Hashed string of the input.</returns>
        public string HashString(string input);
        /// <summary>
        /// Verifies if the input matches the stored Argon2 hash.
        /// </summary>
        /// <param name="input"></param>
        /// <param name="storedHash"></param>
        /// <returns>True or False if both string matches.</returns>
        bool VerifyHash(string input, string storedHash);
        Task<bool> SendEmailAsync(EmailTemplate emailTemplate);
        string HashStringFullEncoded(string input);
    }

    public class DynamicMeths : IDynamicMeths
    {
        #region Props
        private const int WorkFactor = 12; // BCrypt cost factor (default: 10-12 is good)
        #endregion

        #region Meths

        public string HashString(string input)
        {
            if (string.IsNullOrWhiteSpace(input))
            {
                throw new ArgumentNullException(nameof(input), StaticMeths.GetNullOrEmptyOrWhiteSpaceErrorText(nameof(input)));
            }

            // Hash the password with autogenerated salt
            return BCrypt.Net.BCrypt.HashPassword(input, workFactor: WorkFactor);
        }

        public string HashStringFullEncoded(string input)
        {
            // For BCrypt, HashString and HashStringFullEncoded will be the same.
            return HashString(input);
        }

        public bool VerifyHash(string input, string storedHash)
        {
            if (string.IsNullOrWhiteSpace(input))
            {
                throw new ArgumentNullException(nameof(input), StaticMeths.GetNullOrEmptyOrWhiteSpaceErrorText(nameof(input)));
            }
            if (string.IsNullOrWhiteSpace(storedHash))
            {
                throw new ArgumentNullException(nameof(storedHash), StaticMeths.GetNullOrEmptyOrWhiteSpaceErrorText(nameof(storedHash)));
            }

            return BCrypt.Net.BCrypt.Verify(input, storedHash);
        }

        public async Task<bool> SendEmailAsync(EmailTemplate emailTemplate)
        {
            if (emailTemplate is null)
            {
                throw new ArgumentNullException(nameof(emailTemplate));
            }

            try
            {
                MimeMessage message = new();
                message.From.Add(new MailboxAddress(emailTemplate.Title, emailTemplate.FromEmail));
                message.To.Add(new MailboxAddress(emailTemplate.Username, emailTemplate.ToEmail));
                message.Subject = emailTemplate.Subject;

                // Create Email Body (HTML)
                BodyBuilder bodyBuilder = new()
                {
                    HtmlBody = emailTemplate.Body
                };

                message.Body = bodyBuilder.ToMessageBody();

                // Send Email via SMTP
                using SmtpClient smtp = new();
                await smtp.ConnectAsync(emailTemplate.SmtpServer, emailTemplate.SmtpPort, MailKit.Security.SecureSocketOptions.StartTls);
                await smtp.AuthenticateAsync(emailTemplate.FromEmail, emailTemplate.EmailPassword);
                await smtp.SendAsync(message);
                await smtp.DisconnectAsync(true);

                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Email sending failed: {ex.Message}");
                return false;
            }
        }

        #endregion
    }
}
